export class RbacError extends Error { constructor(code, message) { super(message); this.code = code; } }
const requireRole = (actor, role) => { if (actor.role !== role) throw new RbacError('FORBIDDEN', 'The actor is not authorized for this supplier RBAC transition.'); };
export function createRbacRegistry() {
  const roles = new Map(); const grants = new Map(); const audit = [];
  const record = (action, subject, actor, detail = {}) => audit.push({ id: `AUD-${audit.length + 1}`, action, subject, actor, detail, at: new Date().toISOString() });
  const getRole = id => { const role = roles.get(id); if (!role) throw new RbacError('NOT_FOUND', 'The supplier access role was not found.'); return role; };
  const getGrant = id => { const grant = grants.get(id); if (!grant) throw new RbacError('NOT_FOUND', 'The supplier role grant was not found.'); return grant; };
  return {
    defineRole(actor, input) { requireRole(actor, 'access-engineer'); if (!/^ROLE-[A-Z0-9]{3,}$/.test(input.id || '') || !input.supplier || !Array.isArray(input.permissions) || input.permissions.length === 0 || !input.permissions.every(item => /^[a-z]+:[a-z-]+$/.test(item))) throw new RbacError('VALIDATION', 'Identifier, supplier, and valid permission bundle are required.'); if (new Set(input.permissions).size !== input.permissions.length) throw new RbacError('VALIDATION', 'Role permissions must be unique.'); if (roles.has(input.id)) throw new RbacError('CONFLICT', 'The supplier access role identifier already exists.'); const role = { id: input.id, supplier: input.supplier.trim(), permissions: [...input.permissions], state: 'active' }; roles.set(role.id, role); record('role.defined', role.id, actor.id); return { ...role, permissions: [...role.permissions] }; },
    requestGrant(actor, input) { requireRole(actor, 'supplier-manager'); const role = getRole(input.roleId); if (role.state !== 'active') throw new RbacError('CONFLICT', 'Only active supplier roles can be granted.'); if (!input.subjectId || input.subjectId.trim().length < 3 || !input.justification || input.justification.trim().length < 25) throw new RbacError('VALIDATION', 'Subject and detailed grant justification are required.'); const grant = { id: `GRANT-${grants.size + 1}`, roleId: role.id, subjectId: input.subjectId.trim(), justification: input.justification.trim(), state: 'requested', requestedBy: actor.id }; grants.set(grant.id, grant); record('grant.requested', grant.id, actor.id, { roleId: role.id }); return { ...grant }; },
    approveGrant(actor, id) { requireRole(actor, 'access-governor'); const grant = getGrant(id); if (grant.state !== 'requested') throw new RbacError('CONFLICT', 'Only requested supplier role grants can be approved.'); grant.state = 'active'; grant.approvedBy = actor.id; record('grant.approved', id, actor.id, { roleId: grant.roleId }); return { ...grant }; },
    authorize(actor, input) { requireRole(actor, 'access-runtime'); const role = getRole(input.roleId); if (role.state !== 'active') throw new RbacError('CONFLICT', 'The supplier access role is not active.'); const grant = [...grants.values()].find(item => item.roleId === role.id && item.subjectId === input.subjectId && item.state === 'active'); const allowed = Boolean(grant) && role.permissions.includes(input.permission); record(allowed ? 'authorization.allowed' : 'authorization.denied', role.id, actor.id, { subjectId: input.subjectId, permission: input.permission }); return { allowed }; },
    revokeGrant(actor, id, reason) { requireRole(actor, 'access-governor'); const grant = getGrant(id); if (grant.state !== 'active') throw new RbacError('CONFLICT', 'Only active supplier role grants can be revoked.'); if (!reason || reason.trim().length < 15) throw new RbacError('VALIDATION', 'A detailed grant revocation reason is required.'); grant.state = 'revoked'; grant.revokedBy = actor.id; record('grant.revoked', id, actor.id, { reason: reason.trim() }); return { ...grant }; },
    getRole: id => { const role = getRole(id); return { ...role, permissions: [...role.permissions] }; }, getGrant: id => ({ ...getGrant(id) }), audit: () => audit.map(item => ({ ...item })), count: () => roles.size
  };
}
